---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-east-1
  availability_zone: us-east-1e
  security_group_ids:
    - ci-testing
  instance_type: c3.large
  interface: public
  tags:
    Env: public
    Type: test
    Operator: <%= ENV['USER'] %>

transport:
  name: sftp
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero
  log_level: debug
  client_rb:
    environment: dev

platforms:
  - name: ubuntu-14.04
    driver_config:
      image_id: ami-9301c7f8

suites:
  - name: default
    driver:
      tags:
        Name: et-secrets-default-ubuntu-1404
    run_list:
      - recipe[et_consul::server]
      - recipe[et_secrets::default]
      - recipe[et_secrets::vault_init]
      - recipe[et_secrets::renew_vault_token]
      - recipe[tiny_bind::default]
      - recipe[test_replace_vault_token::default]
      - recipe[test_deps::default]
    attributes:
      etc_environment:
        VAULT_ADDR: 'http://localhost:8200'
      et_consul:
        mocking: true
