---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-east-1
  availability_zone: us-east-1e
  security_group_ids:
    - ci-testing
  instance_type: c3.large
  interface: public
  tags:
    Env: public
    Type: test
    Operator: <%= ENV['USER'] %>

transport:
  name: sftp
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero
  client_rb:
    environment: dev

platforms:
  - name: ubuntu-14.04
    driver_config:
      image_id: ami-9301c7f8

suites:
  - name: default
    driver:
      tags:
        Name: et_secrets_default_ubuntu_1404
    run_list:
      - recipe[et_consul::server]
      - recipe[et_secrets::default]
      - recipe[vault_init::default]
      - recipe[tiny_bind::default]
    attributes:
      consul:
        config:
          bootstrap_expect: 1
