---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-east-1
  availability_zone: us-east-1e
  security_group_ids:
    - ci-testing
  instance_type: c3.large
  interface: public
  transport:
    ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero
  client_rb:
    environment: dev

platforms:
  - name: ubuntu-14.04
    driver_config:
      image_id: ami-9301c7f8
      tags:
        Env: public
        Type: test

suites:
  - name: default
    run_list:
      - recipe[zookeeper::default]
      - recipe[zookeeper::service]
      - recipe[et_secrets::default]
    attributes:
      vault:
        config:
          backend:
            zookeeper:
              address: localhost:2181
